name: Build and deploy on push
on:
  push:
    branches:
     - icm-pizza

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            public
            src
            tools
            esbuild.mjs
            package-lock.json
            package.json
            tsconfig.json
          lfs: true

      - uses: actions/setup-node@v4
        with:
          node-version: 16
      
      - run: npm ci

      - run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist

  build-win:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: hubol/electric-lizard@icm-16
        with:
          src-artifact: build
          app-id: clayperson.beatzza
          product-name: Beatzza
          icon-base64: iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAp7SURBVHhe7d0x791WGQfgBCkLG2KuUFVGGDpTVamEWNuBbsxlQmJh4xuwVOrWuRsd2pUlUQVzhWCrEEKdER8gQ6iDTRzH9rV9z/E5x+/zSFasm+QvX+ee33nfY1/n4ZNvnj9/AIT0vf5XICABAIEJAAhMAEBgAgACEwAQmACAwAQABCYAIDABAIEJAAhMAEBgAgACEwAQmACAwAQABCYAIDABAIEJAAhMAEBgAgACEwAQmACAwAQABCYAIDABAIEJAAhMAEBgAgACEwAQmACAwAQABPbwyTfPn/f7NOrxh7/o98719I9/6vfWnXV8W4+HlwTAjMc/7ndq9XaZAX/LMADf+uC9F78O3nj0qN87z5lh8PjLT/u9Vz19/6N+r15aAAhMBTDjRQWQYpb9OvEsVOnMP/j22bN+b9nZ1UDKSuC1VuZXv+x31tVcCYSrALrBfWuDKLQAEFi4FmB1hj+jxN7TFlRe8k/V2ALMudUWbL5qsbEFePDZ5y9+qfEqxWUD4FAp39iAq9U0CGoY9FktBUE/8OfUEgZaAAhMAEBgl2gBkq3cawE4iRYAKE4AQGCvtADhb4LRAnASLQBQnACAwLQAY1oAMqr+TsDwATAmDEikxoE/0AJAYAIAAtMCbKEd4IBp6V/jo8MEwBECgRVbB/5UiSDQAkBgKoAlrc7yR55DGLmiOeN8bX1wSO/MSkAFAIEJAAhMC7CklbI42KPH71L6XFX4GHEBMGjpg5/6gzx1pRDIfa46R8/XNBBmniGY+y5CLQAEJgAgsNgtQKul7o2y9t13+50bvvqq35kK1gLUfL5ytwACoEUrH+qtH+axxQ92p/UwSBSWY8nP18pagDUAIBsBAKV0M//cpcHh9bnfS0wAQGACAAITABCYALiY1RXqie7P7vnzV1T0fHWr/XP/g/Dw+tzvJSYAIDABAIEJAChtXPJ/t3U3/wxbbsnvBPznv/udnd78Yb9zpgveCZjcxe8ETO6O83XGgJ9SAUBgsSuAsZZmutyz2pFzseeYln7+1p+x5/jOqAASfXaarQC6QT9sR41/xtEN2EcLAIElaQFqmX3vbiNaagPGUpa5W8/BGaX1Vnv/3VIde8Ol/+BSAXCvN3/eaABMpe6laxrsW+0ZnKnP104lA0ALAIEJAAjslRYghR/9oN9pwGVK/pxaLP8HmUr2XEq0AiEDwMC/oeVBP9VCCEye/OP/BgROkbwC2KNEtWD2n3GlGX+LWqqCDc/8y10NqAAgMAEAgRVtAVLZ00poAUailf5zSrYDFbQAAiCqUoN/bcDVeExnmAbB6FmAuS8NagEgsEsEwL/+s30DXrpEC7DH4w8v1gLMlc1DSVtjj19jCzA1d4xr5zmj3C2AAGhdjYN86shAuer72skaAJCNACCvo7PkCbMrAgBCEwAQWLhFwI6FwMxSl+9Xf38TZz4XIGQADC4XBJ2Sg+WMvr3F9zd3y+/obr9BiQeCaAEgMAEAgYVuAdZcoj3IXS7XcKnurJbgyHu98W2/Mx/9tUQAbHDJtYLOPYOnhsE/SB0Cqd5bAwGgBYDAVAAbXLYC4BwzlUANs39HBQCBCQAITAtwg/KfHErc9DNHBQAF1DKxCAAITABAYNYAFlyh91/rM898f+PjsKbyUg3rACqAi+k+VMNWo9qPLxoBAIFpARa0UqoenUmzvL+F771vOcZorUEtFZAKAAITABCYFmBBzSVpivIx+ftb+errvV98uWJ7UEsLIAA2KPUBzPkhaSkAploNhFoG/ZgWAAITABCYFmCnM8vP1CVj1mM/sQWYqr0lqLH0HwiAnXJ82M76gCQ/9pVBP1bi6TelQqHmwT5HCwCBqQACKVIBbLwTkDJUABCYAIDABEAQFsWYYw1gg9YGz2nHu2ENoJbn3zNPBQCBCQAITAuwoFTZv8Vaa1DsuEftgLK/HQKgV/OAX9OFQS3HbsGvPVoACCx0BdDqrF8rFUB7VAAQmACAwC7TAmwt52taNLsS5X+bmgiAx19+2u+NfPZ5v0MNBECbtAAQmACAwKpvAWbL/8FSGzD9kop24T5zX/rxoI9LuFYF0H1Q5z6sw+tzv8e6pXPmXF6CFgACEwAQWJUB0F2nH7bF/n36upIUdlMBQGDVXQXYfJfe0RnfFYH9Zs617/xfQxUBkH3QTwmBXVzuuy4tAAQmACCwogHw/5V+qqX8v7ZiawB3D/zpesC4r7+1VmANYJVBH4cWAAITABBYuy3AVmvtgFbgJu3AtakAIDABwCpXaa7t+gEwV+Z3r1VS/n/77NnmDVJTAUBgAgACu85VgPFqf+Wr+2eV8288etTv3ceVgOtqOwC2fDuwwjAo1c8fDQQBcF1aAAhMAEBgAqCArhQftjONLymWakOoiwCAwIo+EizplYCGrgIccdaMPVeVWAS8rqIBMHC7aVr3hsU0BATAdWkBIDABAIFV0QKMpWgHpiWrFuN4W9C1A1qA66ouAHIQAK/bEwj/+OJJv8fVaAEgMAEAgYVoAca0A6+71Q5oAa5LBQCBqQAqsDQDn/1dgc70WPbM/nvPrasL5YULgE5NIXD08twgd0isDdJD53Hllm2BcD4tAAQmACCwkC3AoIZW4N4WYCpHSzCU5ofP14FHt2kHzhE6AMZKhkELIXCXg89uFAL5aQEgMAEAgWkBFpReH0jRFlTXCnS2Prlp9Oeevv9Rv0dqKgAITAVwQw1XCqaOVAdVVgNTGxYLVQNpCYCdWg2EYgEwHdQby/4lAiAtLQAEJgAgMC1AQjW0B+N2YPpNvtOO71Ypv9YGDFwFOIUKAAJTAWRSshpYuoW2+gpgYcHQLcH5qAAgMBVApVLM1mszZ7FqYOvsP2INIB8VAASmAqhUjgqg5LrETSqAIgRApe4ZrHN3BjZ5K7BFwOy0ABCYAIDAtAAVu7dnn7YCTbQBM7QA+agAIDABQLW6md/sn5cAgMCsATRiz3pAs5cBR8z851ABQGAqgIptnfWrfiTYDmb98wmACqS8RXcpDGoPAIO/DC0ABKYCyOTjv7zzv50Fv/3Zn/s9FUBHBVCGAMhkawCkHPydFgLAYK+HFgACUwFkslYBfPHx9/u9PGqrAsz49VIBQGAqgEyWKoDcs//Y2v0BOasBM347VAAQmAogk3EF8MkfXs62Z/bhaxVADtP/iYj6CYDenuv2W5QMgLMHfsfgb5MWAAITABCYADjZ0fJ86e91r0832EoAQGACoFJzs/r0teH1Grz1wXv9Hi0RABt1q/rDBlchABLaGhJLM/jS65CLAIDAHv7+r792I9B3/vb13/u99MY3Al3Zb373euXy07d/0u9Ro8sEwJ4BPPehFAD3mwuAowTHObQAEJgA6HUzzrBBFE23APeW7UuDPXU7EKEFSFn+TwnlfFQAEJgKYIYFwW1yzvpLVANpqQAgsKYDoJsNhm2PI38nlRKzZg5XeR/RqQAgsEvdCbjUu++d7XOuAbBfqWotArcC3yAMyjHw89MCQGACAALTAuykJbiPsr4uKgAITAVQkVqqC7N0HCoACEwFAIGpACAwAQCBCQAITABAYAIAAhMAEJgAgMAEAIT14MF/AUityK8sTcVBAAAAAElFTkSuQmCC
          dst-artifact: build-win
          platform: win
  
  deploy-itch:
    needs: [build, build-win]
    runs-on: ubuntu-latest
    env:
      BUTLER_API_KEY: ${{ secrets.CLAYPERSON_BUTLER_CREDENTIALS }}
    steps:
      - run: wget https://broth.itch.zone/butler/linux-amd64/LATEST/archive.zip
      - run: unzip archive.zip
      - run: chmod +x butler
      - uses: actions/download-artifact@v4
      - run: ./butler push "build" clayperson/beatzza:html5
      - run: ./butler push "build-win" clayperson/beatzza:win
  
  cleanup:
    needs: [ deploy-itch ]
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            build
            build-win
